let x : unit -> int = fun () => {
  try (failwith("oh dear")) {
    | Failure(_) => 15
  };
};

let y : bool -> string = fun (b) => {
  try ({
      if (b) {
        "";
      } else {
        failwith("");
      };
    }) {
    | Failure(_) => ""
  };
};

exception Other(int, bool);

let z : unit -> int = fun () => {
  try (15) {
    | Failure(_) => 12
    | Other(i, _) => i
  };
};

let a = fun () => {
  try (raise (Other (15, true))) {
    | Other(i, b) => (i, b)
  };
};
